alias uu="sudo apt update && sudo apt -y upgrade"
alias rn="react-native start"
alias rna="react-native run-android" 
alias ys="yarn start"
alias emN="emulator -avd Nexus_5X_API_28"
alias es="ssh -R 80:localhost:5000 serveo.net" 
alias vmi="pactl -- set-sink-volume 0 +30%"
alias vmd="pactl -- set-sink-volume 0 -30%"
alias rnar="react-native run-android --variant=release"
alias gp="git push"
alias gpm="git push origin master"
